### ISSUE TITLE
[Feature Request] Add random GUID/UUID 

### ISSUE THREAD

**Issue by orestesgaolin** [PinkFrojd/mock_data#4]
It would be useful to be able to generate UUIDs.

**Comment by dinkopehar** [comment]
Hello @orestesgaolin and thank you for taking interest in this library :smile: .

I can add `UUID/GUID` generate methods, but since this is library used only to mock data (_simulated objects that mimic the behavior of real objects_), I won't create it to be cryptographically secure. You can use https://pub.dev/packages/uuid library for that.

Does recommended solution suits your feature request ?

**Comment by orestesgaolin** [comment]
Yes, that's what I was looking for!

**Comment by dinkopehar** [comment]
I'll add it to `mock_data`. I'll keep this feature open until it's done. Then I'll write here about detailed implementation. :wave:

**Comment by dinkopehar** [comment]
Conclusion:
---

I have added suggested functionality. It was nice feature to add, really missing in `mock_data`.

There are 3 types of UUIDs now available by using `mockUUID` function:
- `mockUUID()` - Generates standard version 4 UUID
- `mockUUID('timestamp-first')` ~ Special type of version 4 UUID. First 8 digits represent time converted to hexadecimal digits while the rest of numbers are random. This is usefull for sorting.
- `mockUUID('null')` ~ Generates null UUID (_00000000-0000-0000-0000-000000000000_).

Also, `mockRange` can be used to generate list of UUIDs.

You can read about all UUIDs at https://www.uuidtools.com/uuid-versions-explained .

Happy coding @orestesgaolin :wave: :smile_cat:

**Comment by orestesgaolin** [comment]
Thank you @dinko-pehar. I really appreciate this!
